import { dbImmediateTransaction } from './database.js';
import { postgresSql } from './postgres.js';

const dbRun = (db, query, params = []) => new Promise((resolve, reject) => {
    db.run(query, params, function onRun(error) {
        if (error) reject(error);
        else resolve({ lastID: this.lastID, changes: this.changes });
    });
});

const dbAll = (db, query, params = []) => new Promise((resolve, reject) => {
    db.all(query, params, (error, rows) => {
        if (error) reject(error);
        else resolve(rows || []);
    });
});

const dbExec = (db, query) => new Promise((resolve, reject) => {
    const sql = postgresSql(query);
    db.exec(sql, (error) => {
        if (error) reject(error);
        else resolve();
    });
});

const addColumnIfMissing = async (db, table, column, definition) => {
    const columns = await dbAll(db, 'SELECT column_name AS name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ?', [table]);
    if (!columns.some((existingColumn) => existingColumn.name === column)) {
        await dbRun(db, `ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    }
};

const migrations = [
    {
        version: 1,
        name: 'create-base-schema',
        up: async (db) => dbExec(db, `
            CREATE TABLE IF NOT EXISTS classes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                grade TEXT NOT NULL,
                class_name TEXT NOT NULL UNIQUE,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS students (
                id BIGINT PRIMARY KEY,
                vorname TEXT NOT NULL,
                nachname TEXT NOT NULL,
                geschlecht TEXT CHECK (geschlecht IN ('männlich', 'weiblich', 'divers') OR geschlecht IS NULL),
                klasse TEXT NOT NULL,
                FOREIGN KEY (klasse) REFERENCES classes(class_name) ON DELETE RESTRICT
            );

            CREATE TABLE IF NOT EXISTS replacements (
                id BIGINT PRIMARY KEY,
                studentID BIGINT REFERENCES students(id)
            );

            CREATE TABLE IF NOT EXISTS teachers (
                id BIGINT PRIMARY KEY,
                vorname TEXT NOT NULL,
                nachname TEXT NOT NULL,
                klasse TEXT,
                email TEXT,
                FOREIGN KEY (klasse) REFERENCES classes(class_name) ON DELETE SET NULL
            );

            CREATE TABLE IF NOT EXISTS rounds (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                timestamp TEXT NOT NULL,
                student_id BIGINT NOT NULL,
                scan_id TEXT,
                source_device_id TEXT,
                recorded_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS expected_donations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id BIGINT NOT NULL,
                amount DOUBLE PRECISION NOT NULL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS received_donations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id BIGINT NOT NULL,
                amount DOUBLE PRECISION NOT NULL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            );
        `),
    },
    {
        version: 2,
        name: 'add-round-scan-metadata',
        up: async (db) => {
            await addColumnIfMissing(db, 'rounds', 'scan_id', 'TEXT');
            await addColumnIfMissing(db, 'rounds', 'source_device_id', 'TEXT');
            await addColumnIfMissing(db, 'rounds', 'recorded_at', 'TEXT');
            await dbRun(db, 'UPDATE rounds SET recorded_at = timestamp WHERE recorded_at IS NULL');
        },
    },
    {
        version: 3,
        name: 'create-database-indexes',
        up: async (db) => dbExec(db, `
            CREATE INDEX IF NOT EXISTS idx_rounds_student_id ON rounds(student_id);
            CREATE INDEX IF NOT EXISTS idx_rounds_timestamp ON rounds(timestamp);
            CREATE INDEX IF NOT EXISTS idx_rounds_student_timestamp ON rounds(student_id, timestamp DESC);
            CREATE UNIQUE INDEX IF NOT EXISTS idx_rounds_scan_id ON rounds(scan_id) WHERE scan_id IS NOT NULL;
            CREATE INDEX IF NOT EXISTS idx_expected_donations_student_id ON expected_donations(student_id);
            CREATE INDEX IF NOT EXISTS idx_received_donations_student_id ON received_donations(student_id);
            CREATE INDEX IF NOT EXISTS idx_replacements_student_id ON replacements(studentID);
        `),
    },
    {
        version: 4,
        name: 'add-admin-smtp-and-station-security',
        up: async (db) => dbExec(db, `
            CREATE TABLE IF NOT EXISTS admin_credentials (
                id BIGINT PRIMARY KEY CHECK (id = 1),
                pin_salt TEXT NOT NULL,
                pin_hash TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS admin_sessions (
                token_hash TEXT PRIMARY KEY,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                expires_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS admin_login_attempts (
                client_key TEXT PRIMARY KEY,
                failed_count BIGINT NOT NULL DEFAULT 0,
                locked_until TEXT,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS smtp_configuration (
                id BIGINT PRIMARY KEY CHECK (id = 1),
                host TEXT NOT NULL,
                port BIGINT NOT NULL,
                security TEXT NOT NULL CHECK (security IN ('tls', 'starttls', 'none')),
                username TEXT,
                password_encrypted TEXT,
                from_address TEXT NOT NULL,
                from_name TEXT NOT NULL,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS station_activity (
                device_id TEXT PRIMARY KEY,
                last_seen_at TEXT NOT NULL,
                last_scan_at TEXT,
                scan_count BIGINT NOT NULL DEFAULT 0
            );

            CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires_at ON admin_sessions(expires_at);
            CREATE INDEX IF NOT EXISTS idx_station_activity_last_seen_at ON station_activity(last_seen_at);
        `),
    },
    {
        version: 5,
        name: 'add-microsoft-graph-mail-provider',
        up: async (db) => {
            await addColumnIfMissing(db, 'smtp_configuration', 'provider', "TEXT NOT NULL DEFAULT 'smtp'");
            await addColumnIfMissing(db, 'smtp_configuration', 'tenant_id', 'TEXT');
            await addColumnIfMissing(db, 'smtp_configuration', 'client_id', 'TEXT');
            await addColumnIfMissing(db, 'smtp_configuration', 'client_secret_encrypted', 'TEXT');
        },
    },
    {
        version: 6,
        name: 'add-scanner-stations',
        up: async (db) => {
            await dbExec(db, `
                CREATE TABLE IF NOT EXISTS scanner_stations (
                    id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    mode TEXT NOT NULL DEFAULT 'allow' CHECK (mode IN ('allow', 'warn', 'block')),
                    classes TEXT NOT NULL DEFAULT '[]',
                    grades TEXT NOT NULL DEFAULT '[]'
                );
                INSERT INTO scanner_stations (id, name) VALUES ('default', 'Standard-Scanner')
                    ON CONFLICT(id) DO NOTHING;
            `);
            await addColumnIfMissing(db, 'rounds', 'source_station_id', 'TEXT');
            await addColumnIfMissing(db, 'rounds', 'source_station_name', 'TEXT');
            await addColumnIfMissing(db, 'rounds', 'station_warning', 'TEXT');
        },
    },
    {
        version: 7,
        name: 'index-live-scan-device-history',
        up: async (db) => dbExec(db, `CREATE INDEX IF NOT EXISTS idx_rounds_device_history
            ON rounds(source_device_id, id DESC) WHERE source_device_id IS NOT NULL;`),
    },
    {
        version: 8,
        name: 'notify-live-scan-changes',
        up: async (db) => dbExec(db, `
            CREATE FUNCTION notify_scan_feed_change() RETURNS trigger AS $$
            DECLARE
                current_row JSONB;
                previous_row JSONB;
            BEGIN
                IF TG_OP = 'TRUNCATE' THEN
                    PERFORM pg_notify('scan_feed_changed', '{}');
                    RETURN NULL;
                END IF;
                IF TG_OP <> 'DELETE' THEN current_row := to_jsonb(NEW); END IF;
                IF TG_OP <> 'INSERT' THEN previous_row := to_jsonb(OLD); END IF;
                PERFORM pg_notify('scan_feed_changed', json_build_object(
                    'studentId', CASE WHEN TG_TABLE_NAME = 'rounds' THEN current_row->>'student_id' ELSE current_row->>'id' END,
                    'previousStudentId', CASE WHEN TG_TABLE_NAME = 'rounds' THEN previous_row->>'student_id' ELSE previous_row->>'id' END,
                    'deviceId', current_row->>'source_device_id',
                    'previousDeviceId', previous_row->>'source_device_id'
                )::text);
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER rounds_notify_scan_feed AFTER INSERT OR UPDATE OR DELETE ON rounds
                FOR EACH ROW EXECUTE FUNCTION notify_scan_feed_change();
            CREATE TRIGGER students_notify_scan_feed AFTER UPDATE OR DELETE ON students
                FOR EACH ROW EXECUTE FUNCTION notify_scan_feed_change();
            CREATE TRIGGER rounds_truncate_scan_feed AFTER TRUNCATE ON rounds
                FOR EACH STATEMENT EXECUTE FUNCTION notify_scan_feed_change();
            CREATE TRIGGER students_truncate_scan_feed AFTER TRUNCATE ON students
                FOR EACH STATEMENT EXECUTE FUNCTION notify_scan_feed_change();
        `),
    },
    {
        version: 9,
        name: 'register-named-scan-devices',
        up: async (db) => {
            await dbExec(db, `
                CREATE TABLE scan_devices (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    device_id TEXT NOT NULL UNIQUE,
                    name TEXT
                );
                INSERT INTO scan_devices (device_id)
                    SELECT device_id FROM station_activity ORDER BY last_seen_at, device_id;
            `);
            await addColumnIfMissing(db, 'station_activity', 'source_station_id', 'TEXT');
        },
    },
    {
        version: 10,
        name: 'notify-client-settings-changes',
        up: async db => dbExec(db, [
            `CREATE OR REPLACE FUNCTION notify_client_settings_change() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                PERFORM pg_notify('scan_settings_changed', '{}');
                RETURN NULL;
            END $$`,
            ...['settings', 'scanner_stations', 'classes'].map(table =>
                `CREATE TRIGGER ${table}_client_change AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON ${table}
                FOR EACH STATEMENT EXECUTE FUNCTION notify_client_settings_change()`),
        ].join(';\n')),
    },
    {
        version: 11,
        name: 'remove-shared-default-scanner',
        up: async db => dbExec(db, `
            INSERT INTO scanner_stations (id, name, mode, classes, grades)
                SELECT 'rules_' || a.device_id, 'Scanner-Regeln', s.mode, s.classes, s.grades
                FROM station_activity a JOIN scanner_stations s ON s.id = a.source_station_id
                JOIN scan_devices d ON d.device_id = a.device_id
                WHERE LEFT(s.id, 6) <> 'rules_'
                ON CONFLICT(id) DO NOTHING;
            DELETE FROM scanner_stations WHERE id = 'default';
            UPDATE settings SET value = (value::jsonb - 'scannerStations')::text WHERE key = 'module_config';
        `),
    },
];

export const getLatestSchemaVersion = () => migrations.at(-1)?.version || 0;

export const runDatabaseMigrations = async () => {
    return dbImmediateTransaction(async (db) => {
        await dbExec(db, `
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version BIGINT PRIMARY KEY,
                name TEXT NOT NULL,
                applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        `);

        const appliedRows = await dbAll(db, 'SELECT version FROM schema_migrations ORDER BY version');
        const appliedVersions = new Set(appliedRows.map((row) => row.version));
        const applied = [];

        for (const migration of migrations) {
            if (appliedVersions.has(migration.version)) continue;

            await migration.up(db);
            await dbRun(
                db,
                'INSERT INTO schema_migrations (version, name) VALUES (?, ?)',
                [migration.version, migration.name]
            );
            applied.push(migration.version);
        }

        const currentVersion = getLatestSchemaVersion();
        await dbExec(db, 'CREATE INDEX IF NOT EXISTS idx_rounds_student_acceptance ON rounds(student_id, id DESC)');

        return { applied, currentVersion };
    });
};
